#version 450

layout(local_size_x = 64) in;

struct Vertex {
    float px, py;
    float cr, cb, cg;
};

layout(std430, binding = 0) buffer Vertices {
    Vertex v[];
};

layout(push_constant) uniform Push {
    float dt;
} pc;

const float angular_speed = 1.5;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= v.length()) return;

    float a = angular_speed * pc.dt;
    float  c = cos(a);
    float s = sin(a);

    vec2 p = vec2(v[i].px, v[i].py);
    v[i].px = c * p.x - s * p.y;
    v[i].py = s * p.x + c * p.y;
    v[i].cr = fract(v[i].cr + pc.dt);
}